
project_id = "xrugepqsqfftnxhahfkp"

[functions.export-emails]
verify_jwt = true

[functions.send-confirmation]
verify_jwt = true

[functions.send-appointment-reminder]
verify_jwt = false

[functions.check-upcoming-appointments]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false
